language: node_js
node_js:
  - 6
  - 8
  - 9
cache:
  directories:
    - node_modules
after_success:
  - npm install --no-save conventional-changelog-eslint
  - npx semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
