language: node_js
node_js:
  - 6
  - 8
cache:
  directories:
    - node_modules
before_install:
  - 'if [[ `npm -v` != 5* ]]; then npm install -g npm@latest; fi'
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
