name: Release
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
      - run: git config --global user.name "Mrm Bot"
      - run: git config --global user.email "${BOT_EMAIL}"
      - run: git remote set-url origin "https://${GH_TOKEN}@github.com/sapegin/mrm.git" > /dev/null 2>&1
      - run: git checkout master
      - run: git reset --hard
      - run: npm ci
      - run: echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
      - run: npx lerna version --yes --create-release=github
      - run: npx lerna publish from-git --yes
